# Generated by Django 6.0.3 on 2026-04-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_items',
            field=models.ManyToManyField(blank=True, to='invoices.invoiceitem'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
