# Generated by Django 6.0.3 on 2026-04-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_remove_invoiceitem_invoice_invoice_invoice_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_items',
        ),
        migrations.AddField(
            model_name='invoice',
            name='items',
            field=models.ManyToManyField(to='invoices.invoiceitem'),
        ),
    ]
